<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function laporanperencanaan_perm() {
    return array(
        'access laporanperencanaan content',
		'access laporanperencanaan laporanperencanaan'
	);
} 

/** 
 * Implementation of hook_menu().
 */

function laporanperencanaan_menu() {


	$items['laporanperencanaan'] = array (
      'title' => 'Laporan Perencanaan per SKPD',
	  'description' => 'Laporan Perencanaan per SKPD',
	  //'title callback' => 'laporanperencanaan_title_callback',	  
      'page callback' => 'laporanperencanaan_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 1,
      'file' => 'laporanperencanaan_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['laporanperencanaanuk'] = array (
      'title' => 'Laporan Perencanaan Kegiatan per SKPD',
	  'description' => 'Laporan Perencanaan Kegiatan per SKPD',
	  //'title callback' => 'laporanperencanaan_title_callback',	  
      'page callback' => 'laporanperencanaan_detiluk_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 2,
      'file' => 'laporanperencanaan_detiluk_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}



?>
