<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function laporankas_perm() {
    return array(
        'access laporankas content',
		'access laporankas laporankas'
	);
} 

/** 
 * Implementation of hook_menu().
 */

function laporankas_menu() {


	$items['laporankas'] = array (
      'title' => 'Laporan Anggaran Kas per SKPD',
	  'description' => 'Laporan Anggaran Kas per SKPD',
	  //'title callback' => 'laporankas_title_callback',	  
      'page callback' => 'laporankas_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporankas_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}



?>
