<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function laporanpenatausahaan_perm() {
    return array(
        'access laporanpenatausahaan content',
		'access laporanpenatausahaan laporanpenatausahaan'
	);
} 

/** 
 * Implementation of hook_menu().
 */

function laporanpenatausahaan_menu() {


	$items['laporanpenatausahaan'] = array (
      'title' => 'Laporan Anggaran Kas per SKPD',
	  'description' => 'Laporan Anggaran Kas per SKPD',
	  //'title callback' => 'laporanpenatausahaan_title_callback',	  
      'page callback' => 'laporantu_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporantu_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}



?>
