<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function laporan_perm() {
    return array(
        'access laporan content',
		'access laporan laporan'
	);
} 

/** 
 * Implementation of hook_menu().
 */

function laporan_menu() {


	$items['laporan'] = array (
      'title' => 'Pelaksanaan APBD Tahun 2017',
	  'description' => 'Pelaksanaan APBD Tahun 2017',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporan_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporan_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['laporanskpd'] = array (
      'title' => 'Laporan Realisasi per SKPD',
	  'description' => 'Laporan Realisasi per SKPD',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporanuk_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporanuk_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	
	/*
	$items['laporankas'] = array (
      'title' => 'Laporan Anggaran Kas per SKPD',
	  'description' => 'Laporan Anggaran Kas per SKPD',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporankas_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporankas_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	*/
    $items['laporandetil'] = array (
      'title' => '',
	  //'title_display' => 'invisible',
	  'description' => 'Laporan Realisasi per Obyek/Rekening',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporan_detil_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporan_detil_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    $items['laporandetiluk'] = array (
      'title' => 'Laporan Realisasi per SKPD',
	  'description' => 'Laporan Realisasi per SKPD',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporan_detiluk_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporan_detiluk_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['laporandetilkeg'] = array (
      'title' => 'Laporan Kegiatan',
	  'description' => 'Laporan Kegiatan',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporan_keg_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporan_keg_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['laporanstd'] = array (
      'title' => 'Laporan STD',
	  'description' => 'Laporan STD',
	  //'title callback' => 'laporan_title_callback',	  
      'page callback' => 'laporan_std_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'laporan_std_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}



?>
