<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function Penatausahaan_perm() {
    return array(
        'access Penatausahaan content',
		'access laporan Penatausahaan'
	);
}

/**
 * Implementation of hook_menu().
 */

function Penatausahaan_menu() {


	$items['Penatausahaan'] = array (
      'title' => 'Anggaran Penatausahaan',
	  'description' => 'Anggaran Penatausahaan',
	  'title callback' => 'Penatausahaan_title_callback',	  
      'page callback' => 'Penatausahaan_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'Penatausahaan_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	


    return $items;
}


function Penatausahaan_title_callback() {
    return t('Anggaran Penatausahaan');
}

 
function Penatausahaan_cron() {

}

